name: Bug report
description: Report a reproducible incorrect behavior.
labels: ['bug']
body:
  - type: textarea
    id: description
    attributes:
      label: Bug
      description: What actually happens.
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Reproduction
      description: Minimal steps or code to reproduce.
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected
      description: What should have happened instead.
    validations:
      required: true

  - type: textarea
    id: environment
    attributes:
      label: Environment (optional)
      description: Runtime, platform, versions, or config if relevant.
    validations:
      required: false

  - type: textarea
    id: fix
    attributes:
      label: Notes (optional)
      description: Analysis or suspected cause, if any.
    validations:
      required: false
