name: Documentation request
description: Identify missing, incorrect, or insufficient documentation that blocks correct usage.
labels: ['documentation']
body:
  - type: textarea
    attributes:
      label: Documentation
      description: What's the problem?
    validations:
      required: true
