name: Research request
description: Flag an unresolved question that requires deliberate investigation.
labels: ['research']
body:
  - type: textarea
    attributes:
      label: Research
      description: Describe the context, and the reasoning over why this reseach needs to be conducted
    validations:
      required: true
